package com.cy.downloader.database.dao;

import android.database.sqlite.SQLiteDatabase;

import com.cy.downloader.database.entity.DownloadInfo;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig downloadInfoDaoConfig;

    private final DownloadInfoDao downloadInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        downloadInfoDaoConfig = daoConfigMap.get(DownloadInfoDao.class).clone();
        downloadInfoDaoConfig.initIdentityScope(type);

        downloadInfoDao = new DownloadInfoDao(downloadInfoDaoConfig, this);

        registerDao(DownloadInfo.class, downloadInfoDao);
    }
    
    public void clear() {
        downloadInfoDaoConfig.getIdentityScope().clear();
    }

    public DownloadInfoDao getDownloadInfoDao() {
        return downloadInfoDao;
    }

}
