package com.cy.downloader.database.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DOWNLOAD_INFO.
 */
public class DownloadInfo implements java.io.Serializable {

    public static final int STATE_DOWNLOAD = 0;       // 下载
    public static final int STATE_DOWNLOADING = 1;    // 下载中
    public static final int STATE_DOWNLOAD_FAILED = 2;// 下载失败
    public static final int STATE_PAUSE = 3;          // 暂停
    public static final int STATE_INSTALL = 4;        // 安装
    public static final int STATE_INSTALLING = 5;     // 安装中
    public static final int STATE_INSTALL_FAILED = 6; // 安装失败
    public static final int STATE_OPEN = 7;           // 打开
    public static final int STATE_UPGRADE = 8;           // 更新

    public long id = -1L; // 自增长id
    public String appName; // 应用名称
    public String size; // 应用的大小，用于展示
    public String deepLink;
    public String packageName; // 应用包名
    public String url;
    public String realUrl;
    public String fileMd5;
    public long progress;
    public long totalSize;
    public int state;  // 下载状态

    public DownloadInfo() {
    }

    public DownloadInfo(Long id) {
        this.id = id;
    }

    public DownloadInfo(Long id, String appName, String size, String deepLink, String packageName, String url, String realUrl, String fileMd5, Long progress, Long totalSize, Integer state) {
        this.id = id;
        this.appName = appName;
        this.size = size;
        this.deepLink = deepLink;
        this.packageName = packageName;
        this.url = url;
        this.realUrl = realUrl;
        this.fileMd5 = fileMd5;
        this.progress = progress;
        this.totalSize = totalSize;
        this.state = state;
    }

    //for splash ad download
    public DownloadInfo(String appName, String url) {
        this.appName = appName;
        this.url = url;
    }

    public long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getSize() {
        return size;
    }

    public void setSize(String size) {
        this.size = size;
    }

    public String getDeepLink() {
        return deepLink;
    }

    public void setDeepLink(String deepLink) {
        this.deepLink = deepLink;
    }

    public String getPackageName() {
        return packageName;
    }

    public void setPackageName(String packageName) {
        this.packageName = packageName;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getRealUrl() {
        return realUrl;
    }

    public void setRealUrl(String realUrl) {
        this.realUrl = realUrl;
    }

    public String getFileMd5() {
        return fileMd5;
    }

    public void setFileMd5(String fileMd5) {
        this.fileMd5 = fileMd5;
    }

    public long getProgress() {
        return progress;
    }

    public void setProgress(Long progress) {
        this.progress = progress;
    }

    public long getTotalSize() {
        return totalSize;
    }

    public void setTotalSize(Long totalSize) {
        if(this.totalSize > 0) {
            return;
        }
        this.totalSize = totalSize;
    }

    public int getState() {
        return state;
    }

    public void setState(int state) {
        this.state = state;
    }

}
